### ISSUE TITLE
AttributeError: 'DataSourceNoCloud' object has no attribute 'vendordata2_raw'

### ISSUE THREAD

**Issue by ubuntu-server-builder** [canonical/cloud-init#3864]
This bug was originally filed in Launchpad as [LP: #1922739](https://bugs.launchpad.net/cloud-init/+bug/1922739)
<details>
<summary>Launchpad details</summary>
<pre>
affected_projects = ['cloud-init (Ubuntu)', 'cloud-init (Ubuntu Xenial)', 'cloud-init (Ubuntu Bionic)', 'cloud-init (Ubuntu Focal)', 'cloud-init (Ubuntu Groovy)', 'cloud-init (Ubuntu Hirsute)']
assignee = falcojr
assignee_name = James Falcon
date_closed = 2021-05-05T20:34:53.232284+00:00
date_created = 2021-04-06T14:10:00.781519+00:00
date_fix_committed = 2021-04-19T16:31:59.016497+00:00
date_fix_released = 2021-05-05T20:34:53.232284+00:00
id = 1922739
importance = high
is_complete = True
lp_url = https://bugs.launchpad.net/cloud-init/+bug/1922739
milestone = None
owner = oddbloke
owner_name = Dan Watkins
private = False
status = fix_released
submitter = oddbloke
submitter_name = Dan Watkins
tags = ['verification-done', 'verification-done-bionic', 'verification-done-focal', 'verification-done-groovy', 'verification-done-hirsute', 'verification-done-xenial']
duplicates = [1924755]
</pre>
</details>

_Launchpad user **Dan Watkins(oddbloke)** wrote on 2021-04-06T14:10:00.781519+00:00_

=== Begin SRU Template ===
[Impact]
In PR #777, we added 'vendordata2' and 'vendordata2_raw' attributes to the DataSource class, but didn't use the upgrade framework to deal with an unpickle after upgrade. Because of this, anybody upgrading their cloud-init from an older version to 21.1 who hasn't also run `cloud-init clean` will have cloud-init fail with a traceback.

The change here should fix that failure.

[Test Plan]
Launch an instance or install a cloud-init package using version earlier than 21.1-19-gbad84ad4-0ubuntu1 (if downgrading also run `cloud-init clean`).

Upgrade to 21.1-19-gbad84ad4-0ubuntu1 or later, then reboot (without running `cloud-init clean`).

On un-patched versions, `cloud-init status` will show error, and there will be a traceback in /var/log/cloud-init.log. Patched versions should show no error or traceback.

[Where problems could occur]
Any problem here would mean we're continuing to unpickle data incorrectly, thus we'd see similar behavior to the bug we're fixing.

[Other Info]
Pull request: https://github.com/canonical/cloud-init/pull/869
Commit: https://github.com/canonical/cloud-init/commit/d132356cc361abef2d90d4073438f3ab759d5964

A test has also been added upstream and to our CI to prevent these types of errors from happening in the future: https://github.com/canonical/cloud-init/blob/master/tests/integration_tests/test_upgrade.py#L107

== End SRU Template ==

== Original Description ==

On a test LXD VM instance, I see:

2021-04-06 14:05:11,296 - util.py[WARNING]: failed stage init
2021-04-06 14:05:11,302 - util.py[DEBUG]: failed stage init
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/cloudinit/cmd/main.py", line 652, in status_wrapper
    ret = functor(name, args)
  File "/usr/lib/python3/dist-packages/cloudinit/cmd/main.py", line 376, in main_init
    init.update()
  File "/usr/lib/python3/dist-packages/cloudinit/stages.py", line 371, in update
    self._store_raw_vendordata(self.datasource.get_vendordata2_raw(),
  File "/usr/lib/python3/dist-packages/cloudinit/sources/__init__.py", line 506, in get_vendordata2_raw
    return self.vendordata2_raw
AttributeError: 'DataSourceNoCloud' object has no attribute 'vendordata2_raw'

**Comment by ubuntu-server-builder** [comment]
_Launchpad user **Dan Watkins(oddbloke)** wrote on 2021-04-06T14:10:32.837405+00:00_


_Launchpad attachments_: [cloud-init.tar.gz](https://api.launchpad.net/devel/cloud-init/+bug/1922739/+attachment/5484743/data)

**Comment by ubuntu-server-builder** [comment]
_Launchpad user **Dan Watkins(oddbloke)** wrote on 2021-04-06T14:28:40.626821+00:00_

Oh, actually, this may be because of the mid-boot reboot that LXD agent installation now causes to happen.

**Comment by ubuntu-server-builder** [comment]
_Launchpad user **Dan Watkins(oddbloke)** wrote on 2021-04-06T14:33:38.922457+00:00_

(I can't reproduce this post-bionic, which lends credence to that hypothesis.)

**Comment by ubuntu-server-builder** [comment]
_Launchpad user **Chad Smith(chad.smith)** wrote on 2021-04-15T18:59:59.289605+00:00_

I see reproduce this with the following:
lxc launch ubuntu-daily: xenial dev-x
lxc exec dev-x -- cloud-init status --wait --long   # confirm no failures from status
lxc exec dev-x reboot
lxc exec dev-x -- cloud-init status --wait --long   # confirm no failures from status
lxc exec dev-x -- add-apt-repository ppa:cloud-init-dev/daily
lxc exec dev-x -- apt-get update
lxc exec dev-x -- apt-get install cloud-init
lxc exec dev-x -- reboot
lxc exec dev-x -- cloud-init status --wait --long   # See failure

**Comment by ubuntu-server-builder** [comment]
_Launchpad user **James P(james-pansarasa)** wrote on 2021-04-16T12:38:44.739615+00:00_

I see this consistently on the two bare metal instances I have running 20.04.2 LTS (5.4.0-72-generic)

**Comment by ubuntu-server-builder** [comment]
_Launchpad user **James Falcon(falcojr)** wrote on 2021-04-16T19:06:01.167627+00:00_

I have a PR here: https://github.com/canonical/cloud-init/pull/869

**Comment by ubuntu-server-builder** [comment]
_Launchpad user **Paul Tötterman(ptman)** wrote on 2021-04-17T05:05:54.713399+00:00_

I'm probably hitting this as well.

dpkg.log:2021-04-16 09:46:40 upgrade cloud-init:all 20.4.1-0ubuntu1~18.04.1 21.1-19-gbad84ad4-0ubuntu1~18.04.1


Apr 17 06:59:03 cloud-init[580]: 2021-04-17 04:59:03,191 - util.py[WARNING]: failed stage init
Apr 17 06:59:03 cloud-init[580]: failed run of stage init
Apr 17 06:59:03 cloud-init[580]: ------------------------------------------------------------
Apr 17 06:59:03 cloud-init[580]: Traceback (most recent call last):
Apr 17 06:59:03 cloud-init[580]:   File "/usr/lib/python3/dist-packages/cloudinit/cmd/main.py", line 652, in status_wrapper
Apr 17 06:59:03 cloud-init[580]:     ret = functor(name, args)
Apr 17 06:59:03 cloud-init[580]:   File "/usr/lib/python3/dist-packages/cloudinit/cmd/main.py", line 376, in main_init
Apr 17 06:59:03 cloud-init[580]:     init.update()
Apr 17 06:59:03 cloud-init[580]:   File "/usr/lib/python3/dist-packages/cloudinit/stages.py", line 371, in update
Apr 17 06:59:03 cloud-init[580]:     self._store_raw_vendordata(self.datasource.get_vendordata2_raw(),
Apr 17 06:59:03 cloud-init[580]:   File "/usr/lib/python3/dist-packages/cloudinit/sources/__init__.py", line 506, in get_vendordata2_raw
Apr 17 06:59:03 cloud-init[580]:     return self.vendordata2_raw
Apr 17 06:59:03 cloud-init[580]: AttributeError: 'DataSourceHetzner' object has no attribute 'vendordata2_raw'
Apr 17 06:59:03 cloud-init[580]: ------------------------------------------------------------

**Comment by ubuntu-server-builder** [comment]
_Launchpad user **Taylor Yu(tlyu)** wrote on 2021-04-17T23:03:42.804920+00:00_

Confirmed that removing/renaming obj.pkl appears to work around this issue without causing obvious problems. This was on Ubuntu 16.04.7 LTS, with DataSourceDigitalOcean.

**Comment by ubuntu-server-builder** [comment]
_Launchpad user **Dan Watkins(oddbloke)** wrote on 2021-04-19T16:31:54.587215+00:00_

A fix for this landed just now in https://github.com/canonical/cloud-init/commit/d132356cc361abef2d90d4073438f3ab759d5964

**Comment by ubuntu-server-builder** [comment]
_Launchpad user **Launchpad Janitor(janitor)** wrote on 2021-04-20T09:49:32.796117+00:00_

Status changed to 'Confirmed' because the bug affects multiple users.

**Comment by ubuntu-server-builder** [comment]
_Launchpad user **Launchpad Janitor(janitor)** wrote on 2021-04-20T09:49:32.796117+00:00_

Status changed to 'Confirmed' because the bug affects multiple users.

**Comment by ubuntu-server-builder** [comment]
_Launchpad user **Launchpad Janitor(janitor)** wrote on 2021-04-20T09:49:32.796117+00:00_

Status changed to 'Confirmed' because the bug affects multiple users.

**Comment by ubuntu-server-builder** [comment]
_Launchpad user **Brian Murray(brian-murray)** wrote on 2021-04-20T21:55:08.289874+00:00_

Hello Dan, or anyone else affected,

Accepted cloud-init into groovy-proposed. The package will build now and be available at https://launchpad.net/ubuntu/+source/cloud-init/21.1-19-gbad84ad4-0ubuntu1~20.10.2 in a few hours, and then in the -proposed repository.

Please help us by testing this new package.  See https://wiki.ubuntu.com/Testing/EnableProposed for documentation on how to enable and use -proposed.  Your feedback will aid us getting this update out to other Ubuntu users.

If this package fixes the bug for you, please add a comment to this bug, mentioning the version of the package you tested, what testing has been performed on the package and change the tag from verification-needed-groovy to verification-done-groovy. If it does not fix the bug for you, please add a comment stating that, and change the tag to verification-failed-groovy. In either case, without details of your testing we will not be able to proceed.

Further information regarding the verification process can be found at https://wiki.ubuntu.com/QATeam/PerformingSRUVerification .  Thank you in advance for helping!

N.B. The updated package will be released to -updates after the bug(s) fixed by this package have been verified and the package has been in -proposed for a minimum of 7 days.

**Comment by ubuntu-server-builder** [comment]
_Launchpad user **Brian Murray(brian-murray)** wrote on 2021-04-20T22:00:46.716948+00:00_

Hello Dan, or anyone else affected,

Accepted cloud-init into focal-proposed. The package will build now and be available at https://launchpad.net/ubuntu/+source/cloud-init/21.1-19-gbad84ad4-0ubuntu1~20.04.2 in a few hours, and then in the -proposed repository.

Please help us by testing this new package.  See https://wiki.ubuntu.com/Testing/EnableProposed for documentation on how to enable and use -proposed.  Your feedback will aid us getting this update out to other Ubuntu users.

If this package fixes the bug for you, please add a comment to this bug, mentioning the version of the package you tested, what testing has been performed on the package and change the tag from verification-needed-focal to verification-done-focal. If it does not fix the bug for you, please add a comment stating that, and change the tag to verification-failed-focal. In either case, without details of your testing we will not be able to proceed.

Further information regarding the verification process can be found at https://wiki.ubuntu.com/QATeam/PerformingSRUVerification .  Thank you in advance for helping!

N.B. The updated package will be released to -updates after the bug(s) fixed by this package have been verified and the package has been in -proposed for a minimum of 7 days.

**Comment by ubuntu-server-builder** [comment]
_Launchpad user **Brian Murray(brian-murray)** wrote on 2021-04-20T22:00:49.199068+00:00_

Hello Dan, or anyone else affected,

Accepted cloud-init into focal-proposed. The package will build now and be available at https://launchpad.net/ubuntu/+source/cloud-init/21.1-19-gbad84ad4-0ubuntu1~20.04.2 in a few hours, and then in the -proposed repository.

Please help us by testing this new package.  See https://wiki.ubuntu.com/Testing/EnableProposed for documentation on how to enable and use -proposed.  Your feedback will aid us getting this update out to other Ubuntu users.

If this package fixes the bug for you, please add a comment to this bug, mentioning the version of the package you tested, what testing has been performed on the package and change the tag from verification-needed-focal to verification-done-focal. If it does not fix the bug for you, please add a comment stating that, and change the tag to verification-failed-focal. In either case, without details of your testing we will not be able to proceed.

Further information regarding the verification process can be found at https://wiki.ubuntu.com/QATeam/PerformingSRUVerification .  Thank you in advance for helping!

N.B. The updated package will be released to -updates after the bug(s) fixed by this package have been verified and the package has been in -proposed for a minimum of 7 days.

**Comment by ubuntu-server-builder** [comment]
_Launchpad user **Brian Murray(brian-murray)** wrote on 2021-04-20T22:02:52.627776+00:00_

Hello Dan, or anyone else affected,

Accepted cloud-init into bionic-proposed. The package will build now and be available at https://launchpad.net/ubuntu/+source/cloud-init/21.1-19-gbad84ad4-0ubuntu1~18.04.2 in a few hours, and then in the -proposed repository.

Please help us by testing this new package.  See https://wiki.ubuntu.com/Testing/EnableProposed for documentation on how to enable and use -proposed.  Your feedback will aid us getting this update out to other Ubuntu users.

If this package fixes the bug for you, please add a comment to this bug, mentioning the version of the package you tested, what testing has been performed on the package and change the tag from verification-needed-bionic to verification-done-bionic. If it does not fix the bug for you, please add a comment stating that, and change the tag to verification-failed-bionic. In either case, without details of your testing we will not be able to proceed.

Further information regarding the verification process can be found at https://wiki.ubuntu.com/QATeam/PerformingSRUVerification .  Thank you in advance for helping!

N.B. The updated package will be released to -updates after the bug(s) fixed by this package have been verified and the package has been in -proposed for a minimum of 7 days.

**Comment by ubuntu-server-builder** [comment]
_Launchpad user **glitsj16(glitsj16)** wrote on 2021-04-20T23:11:28.530734+00:00_

I originally filed https://bugs.launchpad.net/ubuntu/+source/cloud-init/+bug/1924755 and got informed that was a duplicate of this bug. I just installed the proposed fix from https://launchpad.net/ubuntu/+source/cloud-init/21.1-19-gbad84ad4-0ubuntu1~16.04.2. I can confirm this fixes it for me on Xenial.

Thanks to all involved, regards.

**Comment by ubuntu-server-builder** [comment]
_Launchpad user **Taylor Yu(tlyu)** wrote on 2021-04-20T23:37:19.872909+00:00_

Verified on 20.04.2 LTS focal.

Got this in the wild in /var/log/cloud-init.log after upgrading from 20.3-2-g371b392c-0ubuntu1~20.04.1 to 21.1-19-gbad84ad4-0ubuntu1~20.04.1:

2021-04-16 19:42:33,005 - util.py[WARNING]: failed stage init
2021-04-16 19:42:33,009 - util.py[DEBUG]: failed stage init
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/cloudinit/cmd/main.py", line 652, in stat
us_wrapper
    ret = functor(name, args)
  File "/usr/lib/python3/dist-packages/cloudinit/cmd/main.py", line 376, in main
_init
    init.update()
  File "/usr/lib/python3/dist-packages/cloudinit/stages.py", line 371, in update
    self._store_raw_vendordata(self.datasource.get_vendordata2_raw(),
  File "/usr/lib/python3/dist-packages/cloudinit/sources/__init__.py", line 506,
 in get_vendordata2_raw
    return self.vendordata2_raw
AttributeError: 'DataSourceDigitalOcean' object has no attribute 'vendordata2_ra
w'

Installed 21.1-19-gbad84ad4-0ubuntu1~20.04.2; rebooted. Confirmed no traceback in /var/log/cloud-init.log. cloud-init status --long reports:

status: done
time: Tue, 20 Apr 2021 23:32:42 +0000
detail:
DataSourceDigitalOcean

instead of an error as with the previous version.

Thanks!

**Comment by ubuntu-server-builder** [comment]
_Launchpad user **Dan Watkins(oddbloke)** wrote on 2021-04-22T15:52:13.456093+00:00_

For groovy, I'm testing with the `ubuntu:bac1692e9ec7` image, with a serial of 20201210.  First, I confirm that the test does trigger the bug on UPGRADE to the version of cloud-init in the release:

$ CLOUD_INIT_OS_IMAGE=ubuntu:bac1692e9ec7::ubuntu::groovy CLOUD_INIT_CLOUD_INIT_SOURCE=UPGRADE pytest tests/integration_tests/test_upgrade.py::test_subsequent_boot_of_upgraded_package
...
FAILED tests/integration_tests/test_upgrade.py::test_subsequent_boot_of_upgraded_package - assert False

and I then verify that the same test passes with the package in groovy-proposed:

$ CLOUD_INIT_OS_IMAGE=ubuntu:bac1692e9ec7::ubuntu::groovy CLOUD_INIT_CLOUD_INIT_SOURCE=PROPOSED pytest tests/integration_tests/test_upgrade.py::test_subsequent_boot_of_upgraded_package
...
PASSED

**Comment by ubuntu-server-builder** [comment]
_Launchpad user **Dan Watkins(oddbloke)** wrote on 2021-04-22T16:13:03.469927+00:00_

For focal, I'm performing the same process but with the `ubuntu:b321e3832dbb` image, serial of 20201210.

UPGRADE does fail:

$ CLOUD_INIT_OS_IMAGE=ubuntu:b321e3832dbb::ubuntu::focal CLOUD_INIT_CLOUD_INIT_SOURCE=UPGRADE pytest tests/integration_tests/test_upgrade.py::test_subsequent_boot_of_upgraded_package
...
FAILED tests/integration_tests/test_upgrade.py::test_subsequent_boot_of_upgraded_package - assert False

and PROPOSED passes:

$ CLOUD_INIT_OS_IMAGE=ubuntu:b321e3832dbb::ubuntu::focal CLOUD_INIT_CLOUD_INIT_SOURCE=PROPOSED pytest tests/integration_tests/test_upgrade.py::test_subsequent_boot_of_upgraded_package
...
PASSED

**Comment by ubuntu-server-builder** [comment]
_Launchpad user **Dan Watkins(oddbloke)** wrote on 2021-04-22T16:28:00.607308+00:00_

For xenial, I'm performing the same process but with the `ubuntu:bb8e87956495` image, serial of 20201210.

UPGRADE does fail:

$ CLOUD_INIT_OS_IMAGE=ubuntu:bb8e87956495::ubuntu::xenial CLOUD_INIT_CLOUD_INIT_SOURCE=UPGRADE pytest tests/integration_tests/test_upgrade.py::test_subsequent_boot_of_upgraded_package
...
FAILED tests/integration_tests/test_upgrade.py::test_subsequent_boot_of_upgraded_package - assert False

$ CLOUD_INIT_OS_IMAGE=ubuntu:bb8e87956495::ubuntu::xenial CLOUD_INIT_CLOUD_INIT_SOURCE=PROPOSED pytest tests/integration_tests/test_upgrade.py::test_subsequent_boot_of_upgraded_package
...
PASSED

**Comment by ubuntu-server-builder** [comment]
_Launchpad user **James Falcon(falcojr)** wrote on 2021-04-27T18:45:00.554021+00:00_

For regression testing, I ran the suite of cloud-init integration tests against hirsute.

**Comment by ubuntu-server-builder** [comment]
_Launchpad user **Łukasz Zemczak(sil2100)** wrote on 2021-04-27T19:28:01.412174+00:00_

The verification of the Stable Release Update for cloud-init has completed successfully and the package is now being released to -updates.  Subsequently, the Ubuntu Stable Release Updates Team is being unsubscribed and will not receive messages about this bug report.  In the event that you encounter a regression using the package from -updates please report a new bug using ubuntu-bug and tag the bug report regression-update so we can easily find any regressions.

**Comment by ubuntu-server-builder** [comment]
_Launchpad user **Launchpad Janitor(janitor)** wrote on 2021-04-27T19:28:20.676161+00:00_

This bug was fixed in the package cloud-init - 21.1-19-gbad84ad4-0ubuntu1~20.10.2

---------------
cloud-init (21.1-19-gbad84ad4-0ubuntu1~20.10.2) groovy; urgency=medium

  * cherry-pick 83f6bbfb: Fix unpickle for source paths missing run_dir
    (#863) (LP: #1899299)
  * cherry-pick d132356c: fix error on upgrade caused by new vendordata2
    attributes (LP: #1922739)

 -- James Falcon <james.falcon@canonical.com>  Mon, 19 Apr 2021 13:58:19 -0500

**Comment by ubuntu-server-builder** [comment]
_Launchpad user **Launchpad Janitor(janitor)** wrote on 2021-04-27T19:28:46.660806+00:00_

This bug was fixed in the package cloud-init - 21.1-19-gbad84ad4-0ubuntu1~20.04.2

---------------
cloud-init (21.1-19-gbad84ad4-0ubuntu1~20.04.2) focal; urgency=medium

  * cherry-pick 83f6bbfb: Fix unpickle for source paths missing run_dir
    (#863) (LP: #1899299)
  * cherry-pick d132356c: fix error on upgrade caused by new vendordata2
    attributes (LP: #1922739)

 -- James Falcon <james.falcon@canonical.com>  Mon, 19 Apr 2021 14:00:12 -0500

**Comment by ubuntu-server-builder** [comment]
_Launchpad user **Launchpad Janitor(janitor)** wrote on 2021-04-27T19:29:14.683272+00:00_

This bug was fixed in the package cloud-init - 21.1-19-gbad84ad4-0ubuntu1~16.04.2

---------------
cloud-init (21.1-19-gbad84ad4-0ubuntu1~16.04.2) xenial; urgency=medium

  * cherry-pick 83f6bbfb: Fix unpickle for source paths missing run_dir
    (#863) (LP: #1899299)
  * cherry-pick d132356c: fix error on upgrade caused by new vendordata2
    attributes (LP: #1922739)

 -- James Falcon <james.falcon@canonical.com>  Mon, 19 Apr 2021 14:06:47 -0500

**Comment by ubuntu-server-builder** [comment]
_Launchpad user **James Falcon(falcojr)** wrote on 2021-05-05T20:34:55.126662+00:00_

This bug is believed to be fixed in cloud-init in version 21.2. If this is still a problem for you, please make a comment and set the state back to New

Thank you.
