### PR TITLE
config: Def activate_by_schema_keys for p-r mods

### PR DESCRIPTION
**Pull request by aciba90**
## Proposed Commit Message

```
config: Def activate_by_schema_keys for p-r mods
```

## Additional Context

SC-1133
SC-1205

## Test Steps

Merge #1609

## Checklist:

 - [x] My code follows the process laid out in [the documentation](https://cloudinit.readthedocs.io/en/latest/topics/contributing.html)
 - [ ] I have updated or added any unit tests accordingly
 - [ ] I have updated or added any documentation accordingly

### CODE REVIEW

File: cloudinit/config/cc_rightscale_userdata.py [hunk 1]
```diff
@@ -44,6 +44,7 @@
     "distros": [ALL_DISTROS],
     "frequency": PER_INSTANCE,
     "examples": [],
+    "activate_by_schema_keys": [],
```
Comment (blackboxsw) [inline cloudinit/config/cc_rightscale_userdata.py:47]: So, in reviewing this. This module does not work at all currently. It calls `[cloud.get_userdata_raw()` which is a method that doesn't exist and then drops into a very generic, unhelpful exception message.](https://github.com/canonical/cloud-init/blob/main/cloudinit/config/cc_rightscale_userdata.py#L73)   The reason this errors always is
```
2022-07-21 21:10:30,402 - cc_rightscale_userdata.py[DEBUG]: Failed to get raw userdata in module cc_rightscale_userdata 'Cloud' object has no attribute 'get_userdata_raw'
```

So,  this looks like it broke in commit 32362c0ac63f10d7a33e3b95dd91a544a1cbdf5 . I've contacted support at Flexera (which now owns RightScale) to ensure they have no use for this module anymore so that we can remove it instead of fixing it if unneeded. That'd be a separate PR if they concur their products don't use cloud-init.

File: cloudinit/config/cc_phone_home.py [hunk 2]
```diff
@@ -88,6 +88,7 @@
             """
         ),
     ],
+    "activate_by_schema_keys": [],
```
Comment (blackboxsw) [inline cloudinit/config/cc_phone_home.py:91]:
```suggestion
    "activate_by_schema_keys": ["phone_home"],
```

**Review by blackboxsw — CHANGES_REQUESTED** [review]
Minor miss on `phone_home` otherwise +1. 
We need to talk as a team about the potential dropping rightscale_userdata. I'll await feedback from support@flexera.com on this though.

File: cloudinit/config/cc_phone_home.py (hunk 2 above)
Comment (aciba90) [reply cloudinit/config/cc_phone_home.py]: Fixed. The reason to not added in the first place was that this module makes use of the `args` argument, and I wasn't sure which entry-point passes `args` through.

File: cloudinit/config/cc_rightscale_userdata.py (hunk 1 above)
Comment (aciba90) [reply cloudinit/config/cc_rightscale_userdata.py:47]: Thanks for pointing this out. I did diagonally read the modules and did not notice it.

**Comment by aciba90** [comment]
Thanks, @blackboxsw, for the review. Ready to be reviewed after CI.

File: cloudinit/config/cc_phone_home.py (hunk 2 above)
Comment (blackboxsw) [reply cloudinit/config/cc_phone_home.py]: +1 @aciba90 the only way to pass through args is via `cloud-init single -c cc_phone_home <some_yaml_file>` which avoids your skip logic over in cloudinit.config.modules anyway. I too had to spend time digging that path up yesterday too.

Comment (blackboxsw) [reply cloudinit/config/cc_phone_home.py]: not a common use case for sure

**Review by blackboxsw — APPROVED** [review]
LGTM!
