### PR TITLE
Graceful integration test 2

### PR DESCRIPTION
**Pull request by holmanb**
## Proposed Commit Message

```
test: disambiguate resource cleanup from test failure

Add a background thread which is responsible for instance cleanup
in integration tests.
```

## Additional Context
blocked by https://github.com/canonical/cloud-init/pull/5920

I'm happy to reorganize the module as a class to reduce use of globals. This is very much work in progress.

## Test log

Search for the keyword "reaper" in the following example log.

<pre><font color="#26A269">tox</font> -e integration-tests -- <u style="text-decoration-style:solid">tests/integration_tests/test_defaults.py</u>
<font color="#A347BA"><b>integration-tests:</b></font><font color="#2AA1B3"> commands[0]&gt;</font> .tox/integration-tests/bin/python -m pytest --log-cli-level=INFO tests/integration_tests/test_defaults.py

<b>--------------------------------------------------------------------------- live log sessionstart ---------------------------------------------------------------------------</b>
2024-12-11 18:49:36 <font color="#26A269">INFO     </font> integration_testing:clouds.py:75 Settings:
CLOUD_INIT_PKG=cloud-init
CLOUD_INIT_SOURCE=NONE
COLLECT_LOGS=ON_ERROR
EXISTING_INSTANCE_ID=None
INCLUDE_COVERAGE=False
INCLUDE_PROFILE=False
INSTANCE_TYPE=None
KEEP_IMAGE=False
KEEP_INSTANCE=False
LOCAL_LOG_PATH=/tmp/cloud_init_test_logs
OS_IMAGE=focal
OS_IMAGE_TYPE=generic
PLATFORM=lxd_container
RUN_UNSTABLE=False
2024-12-11 18:49:36 <font color="#26A269">INFO     </font> root:reaper.py:50 Starting reaper
2024-12-11 18:49:36 <font color="#26A269">INFO     </font> root:reaper.py:84 [reaper] exhalted in life, to assist others in death
<b>============================================================================ test session starts ============================================================================</b>
platform linux -- Python 3.12.7, pytest-8.3.3, pluggy-1.5.0
cachedir: .tox/integration-tests/.pytest_cache
rootdir: /home/holmanb/ci-a
configfile: tox.ini
<b>collected 3 items                                                                                                                                                           </b>

tests/integration_tests/test_defaults.py::TestDefaults::test_clean_log 
<b>------------------------------------------------------------------------------ live log setup -------------------------------------------------------------------------------</b>
2024-12-11 18:49:36 <font color="#26A269">INFO     </font> integration_testing:clouds.py:142 Launching instance with launch_kwargs:
image_id=ubuntu-daily:b7ad14ea0a26617cf6d834a6b925dcb5270e459a865c97c9ecf426fe69db55bb
user_data=None
username=ubuntu
2024-12-11 18:49:37 <font color="#26A269">INFO     </font> pycloudlib.cloud.LXDContainer:cloud.py:245 [&apos;lxc&apos;, &apos;init&apos;, &apos;ubuntu-daily:b7ad14ea0a26617cf6d834a6b925dcb5270e459a865c97c9ecf426fe69db55bb&apos;, &apos;cloudinit-1212-0149365iw2ltnr&apos;, &apos;--config&apos;, &apos;user.meta-data=public-keys: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCqpCozNyoIR4yR5UGrjUg4HzfDs0voCchtGzRcYc1HO83rgPJGHMSFi5WuiLCZtWMtLShnZBxwouXo03mnYPe1dC1QBas2QZIEgJ9Piq+c3kS/YxIf0R2UNg/laYeRNpNtz5zuC+gBQpz5BWLGL39PUHyW6eBtIdpl2CrOASN56pK6Hk285ZphFVWDc+GyxqM1s1E1qH8NmtX2RKl9/LV/LWcPqwkwWMaV9PmdoiwKekJb9xNJiE0HEwdgE55FCSVzMMxJtGZaSHfva8qDamW/IK5JB7RM5u2aC71yWZI8DOXEPHFxKBWBJO4eMQPLQp4ACq8fEWqzci3Ieu9AzmGBa4PCiWA70flPoU09U8daqoYjZei/az1H0CAObaWeDo/pU8bN4CUX8ap3+RU3UzD5JMcZs9jy2VG1nbrM5CYM9EO4Mt6yT+/vQQbXd9Qvg3KkLM8IUVNUf0yPRb/yqJ3QknQ11LVdhJI8GPFzxC5JxbaqngAoqqE5Da2lHb+60vVXIJdwPgKQCXnD9E40Ej8XwmE3DJciZN8zFl1eNsAQF/wJIdoR7+uKnayMu6DcoOBwNwc2MjPJochkicLz7slpzslAE78XM2AzTZg5z8t4bAN+IWeOdiqlyvBFOVEBuzyVmhbkedvzj/SKciU8RFHup6STEH++ujOgIkBdqJYLPQ== holmanb@arc\n&apos;]
2024-12-11 18:49:43 <font color="#26A269">INFO     </font> pycloudlib.instance:instance.py:493 _wait_for_execute to complete
2024-12-11 18:49:49 <font color="#26A269">INFO     </font> paramiko.transport:transport.py:1944 Connected (version 2.0, client OpenSSH_8.2p1)
2024-12-11 18:49:49 <font color="#26A269">INFO     </font> paramiko.transport:transport.py:1944 Authentication (publickey) successful!
2024-12-11 18:51:50 <font color="#26A269">INFO     </font> pycloudlib.instance:instance.py:515 _wait_for_cloudinit to complete
2024-12-11 18:51:50 <font color="#26A269">INFO     </font> pycloudlib.instance:instance.py:266 executing: sh -c &apos;command -v systemctl&apos;
2024-12-11 18:51:50 <font color="#26A269">INFO     </font> pycloudlib.instance:instance.py:266 executing: cloud-init status --wait --long
2024-12-11 18:51:50 <font color="#26A269">INFO     </font> integration_testing:clouds.py:153 Launched instance: LXDInstance(name=cloudinit-1212-0149365iw2ltnr)
2024-12-11 18:51:50 <font color="#26A269">INFO     </font> pycloudlib.instance:instance.py:266 executing: sudo -- sh -c &apos;cloud-init --version&apos;
2024-12-11 18:51:51 <font color="#26A269">INFO     </font> integration_testing:clouds.py:157 cloud-init version: /usr/bin/cloud-init 24.3.1-0ubuntu0~20.04.1
2024-12-11 18:51:51 <font color="#26A269">INFO     </font> pycloudlib.instance:instance.py:266 executing: sudo -- sh -c &apos;grep serial /etc/cloud/build.info&apos;
2024-12-11 18:51:51 <font color="#26A269">INFO     </font> integration_testing:clouds.py:163 image serial: 20241127
<b>------------------------------------------------------------------------------- live log call -------------------------------------------------------------------------------</b>
2024-12-11 18:51:51 <font color="#26A269">INFO     </font> pycloudlib.instance:instance.py:266 executing: sudo -- sh -c &apos;cat /var/log/cloud-init.log&apos;
2024-12-11 18:51:51 <font color="#26A269">INFO     </font> pycloudlib.instance:instance.py:266 executing: sudo -- sh -c &apos;cloud-init status --format=json&apos;
2024-12-11 18:51:51 <font color="#26A269">INFO     </font> pycloudlib.instance:instance.py:266 executing: sudo -- sh -c &apos;grep --count Traceback /var/log/cloud-init.log&apos;
2024-12-11 18:51:51 <font color="#26A269">INFO     </font> pycloudlib.instance:instance.py:266 executing: sudo -- sh -c &apos;cloud-init status --long&apos;
2024-12-11 18:51:52 <font color="#26A269">INFO     </font> pycloudlib.instance:instance.py:266 executing: sudo -- sh -c &apos;cloud-init schema --system --annotate&apos;
<font color="#26A269">PASSED                                                                                                                                                                [ 33%]</font>
tests/integration_tests/test_defaults.py::TestDefaults::test_inactive_modules 
<b>------------------------------------------------------------------------------- live log call -------------------------------------------------------------------------------</b>
2024-12-11 18:51:52 <font color="#26A269">INFO     </font> pycloudlib.instance:instance.py:266 executing: sudo -- sh -c &apos;cat /var/log/cloud-init.log&apos;
<font color="#26A269">PASSED</font><font color="#A2734C">                                                                                                                                                                [ 66%]</font>
tests/integration_tests/test_defaults.py::TestDefaults::test_var_log_cloud_init_output_not_world_readable 
<b>------------------------------------------------------------------------------- live log call -------------------------------------------------------------------------------</b>
2024-12-11 18:51:52 <font color="#26A269">INFO     </font> pycloudlib.instance:instance.py:266 executing: sudo -- sh -c &apos;test -f /var/log/cloud-init-output.log&apos;
2024-12-11 18:51:52 <font color="#26A269">INFO     </font> pycloudlib.instance:instance.py:266 executing: sudo -- sh -c &apos;stat -c %a:%U:%G /var/log/cloud-init-output.log&apos;
<font color="#26A269">PASSED</font><font color="#A2734C">                                                                                                                                                                [100%]</font>
<b>----------------------------------------------------------------------------- live log teardown -----------------------------------------------------------------------------</b>
2024-12-11 18:51:52 <font color="#26A269">INFO     </font> root:reaper.py:41 Instance cloudinit-1212-0149365iw2ltnr submitted to reaper.
2024-12-11 18:51:52 <font color="#26A269">INFO     </font> root:reaper.py:69 Destroying instance cloudinit-1212-0149365iw2ltnr
<b>-------------------------------------------------------------------------- live log sessionfinish ---------------------------------------------------------------------------</b>
2024-12-11 18:51:52 <font color="#26A269">INFO     </font> root:reaper.py:57 Instructing reaper to stop
2024-12-11 18:51:55 <font color="#26A269">INFO     </font> root:reaper.py:109 Reaper destroyed instance cloudinit-1212-0149365iw2ltnr.
2024-12-11 18:51:55 <font color="#26A269">INFO     </font> root:reaper.py:119 Exiting reaper
2024-12-11 18:51:55 <font color="#26A269">INFO     </font> root:reaper.py:131 [reaper] duties complete, my turn to rest
2024-12-11 18:51:55 <font color="#26A269">INFO     </font> root:reaper.py:63 Reaper stopped

<font color="#A2734C">============================================================================= warnings summary ==============================================================================</font>
tests/integration_tests/test_defaults.py::TestDefaults::test_clean_log
tests/integration_tests/test_defaults.py::TestDefaults::test_clean_log
tests/integration_tests/test_defaults.py::TestDefaults::test_clean_log
tests/integration_tests/test_defaults.py::TestDefaults::test_clean_log
tests/integration_tests/reaper.py:114
  /home/holmanb/ci-a/tests/integration_tests/reaper.py:114: DeprecationWarning: isSet() is deprecated, use is_set() instead
    if EXIT_REAPER.isSet():

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
<font color="#A2734C">================================================================= </font><font color="#26A269">3 passed</font>, <font color="#A2734C"><b>5 warnings</b></font><font color="#A2734C"> in 139.14s (0:02:19) =================================================================</font>
<font color="#26A269">  integration-tests: OK (143.73=setup[0.06]+cmd[143.68] seconds)</font>
<font color="#26A269">  congratulations :) (143.84 seconds)</font>
</pre>
## Merge type

- [x] Squash merge using "Proposed Commit Message"
- [ ] Rebase and merge unique commits. Requires commit messages per-commit each referencing the pull request number (#<PR_NUM>)

### CODE REVIEW

File: tests/integration_tests/reaper.py [hunk 1]
```diff
@@ -0,0 +1,194 @@
...
+import threading
+import warnings
+from typing import Final, List
+
+from tests.integration_tests.instances import IntegrationInstance
+
+LOG = logging.getLogger()
+
+
+class Reaper:
```
Comment (TheRealFalcon) [inline tests/integration_tests/reaper.py:23]: Based on the immediate instantiation afterwards I'm assuming this class is intended to be used as a singleton? If so, I think we should make the class name `_Reaper` so that it's more obvious.

But there's two instances. In conftest.py, you instantiate a new instance, but then in instances.py you reference the instance created in this file.

Also, the module docstring is out of date and I think function names like `reaper_start()` and `reaper_stop()` can be updated to just `start()` and `stop()` if they live inside the class.

Comment (holmanb) [reply tests/integration_tests/reaper.py:23]: > I'm assuming this class is intended to be used as a singleton

Yes

> But there's two instances.

Ahhhhhh, nice catch

File: tests/integration_tests/reaper.py [hunk 2]
```diff
@@ -0,0 +1,198 @@
...
+            LOG.info(
+                "Reaper: reaped %s/%s instances",
+                self.counter,
+                self.counter + len(self.undead_ledger),
+            )
+            return True
+
+        # attempt to destroy all instances which previously refused to
+        # destroy
+        for instance in self.undead_ledger:
```
Comment (TheRealFalcon) [inline tests/integration_tests/reaper.py:173]: This seems like an unlikely situation, but if we happen to get a buildup of undead instances, then we could hit a scenario where we finished testing right after we started this list and will sit waiting for a bunch of instances to die that will likely never die.

Think it's worth a `reaped_instances.empty()` check for every new item in the for loop?

**Review by TheRealFalcon — CHANGES_REQUESTED** [review]
This will be a nice improvement! I left a few inline comments, but nothing major.

File: tests/integration_tests/reaper.py [hunk 3]
```diff
@@ -0,0 +1,198 @@
...
+        self.reaper_thread.start()
+
+    def stop(self):
+        """Stop the reaper background thread and wait for completion."""
+        LOG.info("Reaper: stopping")
+        self.exit_reaper.set()
+        with self.wake_reaper:
+            self.wake_reaper.notify()
+            LOG.info("Reaper: awakened to reap")
+        if self.reaper_thread:
```
Comment (TheRealFalcon) [inline tests/integration_tests/reaper.py:85]: (suggestion (now deleted) from previous review was on the wrong line)
```suggestion
        if self.reaper_thread and reaper_thread.is_alive():
```

File: tests/integration_tests/reaper.py [hunk 4]
```diff
@@ -0,0 +1,198 @@
...
+                # race: an instance was added to the queue after iteration
+                # completed. Destroy the latest instance.
+                self._update_undead_ledger(new_undead_instances)
+                return False
+            self._update_undead_ledger(new_undead_instances)
+            LOG.info("Reaper: exiting")
+            if self.undead_ledger:
+                # undead instances exist - unclean teardown
+                LOG.info(
+                    "Reaper: the faults of incompetent abilities will be "
```
Comment (TheRealFalcon) [inline tests/integration_tests/reaper.py:157]: This shouldn't fit as well as it does :joy:

File: tests/integration_tests/reaper.py [hunk 5]
```diff
@@ -0,0 +1,194 @@
...
+        # end of tests
+        self.exit_reaper: Final[threading.Event] = threading.Event()
+
+        # List of instances which temporarily escaped death
+        # The primary porpose of the reaper is to coax these instance towards
+        # eventual demise and report their insubordination on shutdown.
+        self.undead_ledger: Final[List[IntegrationInstance]] = []
+
+        # Queue of newly reaped instances
+        self.reaped_instances: Final[queue.Queue[IntegrationInstance]] = (
```
[the remark this answers is not in the document]
Comment (holmanb) [reply tests/integration_tests/reaper.py:47]: Why? This syntax should be valid 3.8.

FWIW mypy already reports errors on 3.8, so even if it didn't work on 3.8 this wouldn't be be anything new.
```
tests/unittests/cmd/devel/test_logs.py:145: error: Need type annotation for "tar_kwargs" (hint: "tar_kwargs: Dict[<type>, <type>] = ...")  [var-annotated]
tests/unittests/cmd/devel/test_logs.py:149: error: Unused "type: ignore" comment  [unused-ignore]
```

File: tests/integration_tests/reaper.py (hunk 4 above)
Comment (holmanb) [reply tests/integration_tests/reaper.py:157]: Heh :)

I was originally planning to remove the weird personification of this background thread, but it grew on me a little. If anyone objects I can remove it.

File: tests/integration_tests/reaper.py [hunk 6]
```diff
@@ -0,0 +1,198 @@
...
+
+        self.reaped_instances.put(instance)
+        with self.wake_reaper:
+            self.wake_reaper.notify()
+            LOG.info("Reaper: awakened to reap")
+
+    def start(self):
+        """Spawn the reaper background thread."""
+        LOG.info("Reaper: starting")
+        self.reaper_thread = threading.Thread(
```
[the remark this answers is not in the document]
Comment (holmanb) [reply tests/integration_tests/reaper.py:73]: > If that's a valid use case

I wasn't necessarily planning on it being a non-singleton, but I'm trying to make it robust (including in using it in ways that weren't originally intended) so I've added your suggestions. Thanks!

File: tests/integration_tests/reaper.py (hunk 2 above)
Comment (holmanb) [reply tests/integration_tests/reaper.py:173]: > scenario where we finished testing right after we started this list and will sit waiting for a bunch of instances to die that will likely never die.

Yeah, that could happen. Good point.

> Think it's worth a reaped_instances.empty() check for every new item in the for loop?

That alone wouldn't work, I suspect. A majority of the time when this code is running reaped_instances.empty() is probably true, since we removed all instanced from this queue just before running this code. But if `self.exit_reaper.is_set() and self.reaped_instances.empty()` then we can probably exit early to avoid the extra waiting.

File: tests/integration_tests/reaper.py (hunk 5 above)
[the remark this answers is not in the document]
Comment (TheRealFalcon) [reply tests/integration_tests/reaper.py:47]:
```
Python 3.8.16 (default, Jul 22 2023, 21:38:13) 
[GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from queue import Queue
>>> x: Queue[str] = Queue()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'type' object is not subscriptable
>>> x: Queue = Queue()
>>> 
```

https://docs.python.org/3/whatsnew/3.9.html#type-hinting-generics-in-standard-collections

File: tests/integration_tests/reaper.py (hunk 4 above)
Comment (TheRealFalcon) [reply tests/integration_tests/reaper.py:157]: No objections from me!

**Review by TheRealFalcon — APPROVED** [review]
LGTM!

**Comment by holmanb** [comment]
Thanks for the reviews @TheRealFalcon!
